### ISSUE TITLE
Find Files from User and from Domain 

### ISSUE THREAD

**Issue by Alan-TEECOM** [bimone/BIMOne.GoogleSheets#3]
Hi Vincent, 
Great work, these nodes works like a charm, thank you. 

Right now the GetGoogleSheetInGoogleDrive only finds sheets directly shared with (owned by) user, any chance you could include a option for the domain corpora so that it can find any searchable sheet within the domain?

That way different user can use it to write to the same sheet even it hasn't be shared with them (I guess)

https://developers.google.com/drive/api/v3/reference/files/list?apix_params=%7B%22corpora%22%3A%22allDrives%22%2C%22includeItemsFromAllDrives%22%3Atrue%2C%22includeTeamDriveItems%22%3Atrue%2C%22q%22%3A%22name%20contains%20%5C%22alan%5C%22%22%2C%22supportsAllDrives%22%3Atrue%2C%22supportsTeamDrives%22%3Atrue%7D

Many thanks!

**Comment by vinnividivicci** [comment]
Hello @Alan-TEECOM , I have made the changes to the codebase and submitted a new version to the Dynamo package manager (v 1.1.0) However, I'm not sure that the package worked properly or maybe there's a lag between publishing and it appearing in Revit.

In any case, you can update to the latest version by dropping the DLLs in [this release](https://github.com/bimone/BIMOne.GoogleSheets/releases/tag/1.1.0) into the following folder:
%APPDATA%\Dynamo\Dynamo Revit\2.0\packages\BIMOneGoogleAPI\bin

Hope that helps!

**Comment by Alan-TEECOM** [comment]
Hi Vincent, thanks, it worked fine, and the package manager worked properly as well, have a great day!
