### ISSUE TITLE
Im new and Im from Peru

### ISSUE THREAD

**Issue by Kenjial** [bimone/BIMOne.GoogleSheets#6]
Hello I dont know if Im in the correct place to ask for help. I just download the BIM ONE dynamo package but when i was trying to see the sample looks like the image is blocked or lost. I've been trying to see what to do after put my cedentials in the extra file but im loss. I think that a image of the sample usage will be of so much help.
Thank you for ur time.
Kenji Asto
Student from Universidad de Lima

**Comment by jmcouffin** [comment]
Not sure what the question is. 
I checked all the links and images on github repo, they are fine. 
Check this post to get you further maybe https://forum.dynamobim.com/t/how-to-connect-dynamo-to-a-web-based-system/11412/34

**Comment by Kenjial** [comment]
Thank u so much, i found a usage image of bimone

**Comment by Kenjial** [comment]
https://bimone.com/en/Blog/DynamoPackageGoogleSheets in this page there is a way to use the package BimOne, but looks like is lose
![image](https://user-images.githubusercontent.com/109120861/178612587-855c3705-79d4-44cd-9db3-40aa5d7a7e25.png)
i just check the link jmcouffin and copy the model in here ''
![image](https://user-images.githubusercontent.com/109120861/178613181-067fbdb6-4e5d-4d4c-9b6e-8443f209d203.png)
 '' but i got some alerts 
![image](https://user-images.githubusercontent.com/109120861/178613090-205f174e-d3c1-44c9-9a59-1ecf9b1ec11b.png)
Maybe is my account in gmail that is a coporative one?

**Comment by jmcouffin** [comment]
The first node in yellow on the left is probably giving you a more detailed explaination, but the thing is: 
- you are trying to filter in your drive for a sheet with the name 'Your GoogleSheet Name' -> Does it exist? Probably not unless you created it.

The second yellow node is telling you something in the yellow pop bubble on top, it is trying to: 
- append [] (empty list) data to a tab named 'sheet name' in 'Your GoogleSheet Name' (that does not exist yet as you did not create it. 

Try to organize what you are trying to achieve before assembling the whole process:
- I want to create a gsheet
- get its id
- to be able to write data in it
- or maybe later append data (not overwriting the previous data)

that should help you get going in the meantime I will close the issue as it is not related to the code itself, but more about you learning how to do things (-> [dynamo forums](https://forum.dynamobim.com/))

an example with comments:
![gsheet](https://user-images.githubusercontent.com/7872003/178947274-4dd73c01-4e24-417e-a536-1344c33c120c.png)

and a sample file
[gsheet.zip](https://github.com/bimone/BIMOne.GoogleSheets/files/9110387/gsheet.zip)
